# Build settings
markdown: kramdown
highlighter: rouge/pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
blog:
    name: willgo
    description: 最好的从未错过
    title: Will go, Just do it.
    url: index.html
    duoshuo: 5312914
    tongji: will_go8
    qiniu: 979827772@qq.com
author:
    name: Will.Quan
    email: WillQuan0815@gmail.com
    weibo: http://weibo.com/u/2369015654
    github: https://github.com/will0815/will0815.github.io
